# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(choices=[(b'cafe', b'Cafe'), (b'pizza', b'Pizza'), (b'pub', b'Pub'), (b'global', b'Global'), (b'turkish', b'Turkish'), (b'chinese', b'Chinese'), (b'bistro', b'Bistro')], default=b'cafe', max_length=200),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
