# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='restaurant_address',
        ),
    ]
