# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_auto_20181030_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='restaurant_rating',
        ),
    ]
