# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20181105_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default=b'name', max_length=200),
        ),
    ]
