# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20181104_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customer_name',
            new_name='name',
        ),
    ]
