# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20181028_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_services',
            field=models.BooleanField(default=False),
        ),
    ]
