# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20181105_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
