# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_auto_20181105_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
