# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_auto_20181105_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tag',
            field=models.CharField(choices=[(b'cafe', b'Cafe'), (b'pizza', b'Pizza'), (b'pub', b'Pub'), (b'global', b'Global'), (b'bistro', b'Bistro')], default=b'cafe', max_length=200),
        ),
    ]
