# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_auto_20181028_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='monday_closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
