# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_auto_20181028_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu_already_online',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_link',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(choices=[(b'cafe', b'Cafe'), (b'pizza', b'Pizza'), (b'pub', b'Pub'), (b'global', b'Global'), (b'turkish', b'Turkish'), (b'chinese', b'Chinese'), (b'bistro', b'Bistro')], max_length=200),
        ),
    ]
