# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_auto_20181029_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
