# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_auto_20181030_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
