# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-30 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0017_auto_20181030_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='friday_closing_time',
            new_name='friday_hours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='friday_opening_time',
            new_name='monday_hours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='monday_closing_time',
            new_name='saturday_hours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='monday_opening_time',
            new_name='sunday_hours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='saturday_closing_time',
            new_name='thursday_hours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='saturday_opening_time',
            new_name='tuesday_hours',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='sunday_closing_time',
            new_name='wednesday_hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='sunday_opening_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='thursday_closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='thursday_opening_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tuesday_closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='tuesday_opening_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='wednesday_closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='wednesday_opening_time',
        ),
    ]
