# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-28 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20181028_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
